/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A_EDialog: typeof import('./src/components/A_EDialog/A_EDialog.vue')['default']
    BsWrapper: typeof import('./src/components/bsWrapper/bsWrapper.vue')['default']
    CustomDrawer: typeof import('./src/components/customDrawer/customDrawer.vue')['default']
    CustomTable: typeof import('./src/components/customTable/customTable.vue')['default']
    DarkThemeSwitch: typeof import('./src/components/darkThemeSwitch/darkThemeSwitch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    JumpPageBtn: typeof import('./src/components/jumpPageBtn/jumpPageBtn.vue')['default']
    ListQueryForm: typeof import('./src/components/listQueryForm/listQueryForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
